<a href="https://colab.research.google.com/github/Eswa2020/urban-parking-prediction-models/blob/master/COL_parking__prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Importing libraries and loading dataset

In [ ]:


#importimg our libraries to use
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#let's load the  dataset
datak=pd.read_csv("/content/drive/MyDrive/city-of-columbus-park-mobile-parking-meter-transactions-01-2019-01-2020-1.csv",encoding='ISO-8859-1')
datak.head(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,supplier,zone
0,2:19:15,Short North Mobile Pay Only,2019-02-22 21:59:00.000,2019-02-22 19:40:00.000,$7.00,2019-02-22 19:40:00.000,Columbus,1002
1,2:00:00,Short North Mobile Pay Only,2019-04-05 19:18:00.000,2019-04-05 17:18:00.000,$6.00,2019-04-05 17:19:00.000,Columbus,2007

In [ ]:
datak.tail(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,supplier,zone
434460,0:15:00,Short North Metered,2019-08-21 21:28:00.000,2019-08-21 21:13:00.000,$0.50,2019-08-22 03:45:00.000,Columbus,31029
434461,0:15:00,Short North Metered,2019-08-21 21:24:00.000,2019-08-21 21:09:00.000,$0.50,2019-08-22 03:45:00.000,Columbus,31040

## Exploring our dataset

In [ ]:
datak.shape

(434462, 8)

In [ ]:
datak.isna().sum()

duration              0
location              0
parking_end_date      0
parking_start_date    0
parkingamount         0
paymentdate           0
supplier              0
zone                  0
dtype: int64

In [ ]:
datak.duplicated().sum()

np.int64(2343)

In [ ]:
datak.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434462 entries, 0 to 434461
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   duration            434462 non-null  object
 1   location            434462 non-null  object
 2   parking_end_date    434462 non-null  object
 3   parking_start_date  434462 non-null  object
 4   parkingamount       434462 non-null  object
 5   paymentdate         434462 non-null  object
 6   supplier            434462 non-null  object
 7   zone                434462 non-null  int64
dtypes: int64(1), object(7)
memory usage: 26.5+ MB

##Univariate Analysis

##In-depth Exploration using SQL

In [ ]:
!pip install pandas
!pip install sqlalchemy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [ ]:
import sqlite3
from sqlalchemy import create_engine

# connect to the database
conn = sqlite3.connect('example.db')

# create engine
engine = create_engine('sqlite:///example.db')

In [ ]:
#load the sql into our  environment
%load_ext sql

In [ ]:
#connect to our memory sqlite database
%sql sqlite://

In [ ]:
#importimg our libraries to use
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime
%matplotlib inline

In [ ]:
#we first convert our database into csv so that we can run in the  sql environment
# converting to CSV file
dataq3=datak.to_csv('raw_data.csv', index=False)

In [ ]:
!add-apt-repository -y ppa:sergey-dryabzhinsky/packages
!apt update
!apt install sqlite3

Repository: 'deb https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu/ jammy main'
Description:
Some packages that absent in main Ubuntu repos or backported:
- opensslXXXr - for php-mod-openssl different versions
- libvpx1 (xenial) - for php-5.4
- mysql-5.5 (xenial) - libmysqlclient16 for php 4.4-5.4
- pcre3 - for php, build without stack recursion
- geoip-database - full set of latest GeoIP-lite v1 databases

== Attention! ==

@2022-05-18
Soon most of backported libraries will be moved to `backports` ppa.
And this and other PPAs will depend on `backports`.

@2019-05-28
Updated symbols in libssl102r!
Dependant packages may fail to run!
Wait till these packages will be rebuilded: php54, php55, php56, php-mod-mongodb, php7-mod-stomp.

@2019-05
Precise packages removed.

@2017-05
Beware! Precise is obsolete and packages will not be updated!
For Precise packages follow https://dryabzhinsky.noip.me/packages/

@2015-05
Beware! Lucid is obsolete and packages will not be updated!
For Lucid packages follow https://dryabzhinsky.noip.me/packages/

== Changes ==

@2017-09
Start testing armhf + arm64 toolchain and rebuild packages.
More info: https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/packages
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/sergey-dryabzhinsky-ubuntu-packages-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/sergey-dryabzhinsky-ubuntu-packages-jammy.list
Adding key to /etc/apt/trusted.gpg.d/sergey-dryabzhinsky-ubuntu-packages.gpg with fingerprint 57222E12FE3B2F6B6C852D005BACA02E04AF8135
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,311 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,935 kB]
Get:9 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [89.0 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,898 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:13 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy InRelease [18.3 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.0 MB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,151 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,968 kB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,233 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,623 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.9 kB]
Get:22 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy/main amd64 Packages [13.1 kB]
Fetched 38.7 MB in 4s (8,770 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,508 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
49 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libsqlite3-0 libsqlite3-dev
Suggested packages:
  libsqlite3-0-plugins sqlite3-doc
The following NEW packages will be installed:
  sqlite3
The following packages will be upgraded:
  libsqlite3-0 libsqlite3-dev
2 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 1,387 kB of archives.
After this operation, 748 kB disk space will be freed.
Get:1 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy/main amd64 libsqlite3-dev amd64 3.40.1-2sergeyd10.7~22.04.1 [729 kB]
Get:2 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy/main amd64 libsqlite3-0 amd64 3.40.1-2sergeyd10.7~22.04.1 [548 kB]
Get:3 https://ppa.launchpadcontent.net/sergey-dryabzhinsky/packages/ubuntu jammy/main amd64 sqlite3 amd64 3.40.1-2sergeyd10.7~22.04.1 [110 kB]
Fetched 1,387 kB in 2s (580 kB/s)
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../libsqlite3-dev_3.40.1-2sergeyd10.7~22.04.1_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.40.1-2sergeyd10.7~22.04.1) over (3.37.2-2ubuntu0.5) ...
Preparing to unpack .../libsqlite3-0_3.40.1-2sergeyd10.7~22.04.1_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.40.1-2sergeyd10.7~22.04.1) over (3.37.2-2ubuntu0.5) ...
Selecting previously unselected package sqlite3.
Preparing to unpack .../sqlite3_3.40.1-2sergeyd10.7~22.04.1_amd64.deb ...
Unpacking sqlite3 (3.40.1-2sergeyd10.7~22.04.1) ...
Setting up libsqlite3-0:amd64 (3.40.1-2sergeyd10.7~22.04.1) ...
Setting up libsqlite3-dev:amd64 (3.40.1-2sergeyd10.7~22.04.1) ...
Setting up sqlite3 (3.40.1-2sergeyd10.7~22.04.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

In [ ]:
import sqlite3
print(sqlite3.sqlite_version) # 3.33.0

3.37.2

In [ ]:
import sqlite3

# Read data into pandas DataFrame
with open('raw_data.csv', 'r') as f:
    data = pd.read_csv(f, index_col=0, encoding='utf-8')

# Create connection to SQLite database
conn= sqlite3.connect('mydatabase.db')

# Write DataFrame to SQLite database
data.to_sql('mytable', conn)

# Query data from SQLite database using SQL
sql_query = """
SELECT * FROM mytable LIMIT 5;
"""

result = pd.read_sql_query(sql_query, conn)

# Close connection to SQLite database
conn.close()

# Show the result
result.head(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,supplier,zone
0,2:19:15,Short North Mobile Pay Only,2019-02-22 21:59:00.000,2019-02-22 19:40:00.000,$7.00,2019-02-22 19:40:00.000,Columbus,1002
1,2:00:00,Short North Mobile Pay Only,2019-04-05 19:18:00.000,2019-04-05 17:18:00.000,$6.00,2019-04-05 17:19:00.000,Columbus,2007

In [ ]:
#we try and get the number of zones from columbus city data
#Query data from SQLite database using SQL

sql_query = """
SELECT COUNT( DISTINCT zone) AS "Number of col zones" from mytable;
"""
# Create connection to SQLite database
conn1 = sqlite3.connect('mydatabase.db')

result1 = pd.read_sql_query(sql_query, conn1)

# Show the result
result1.head()

   Number of col zones
0                  179

In [ ]:
#we try and what are the suppliers in columbus city
#Query data from SQLite database using SQL

sql_query = """
SELECT COUNT( DISTINCT supplier) AS "Number of col suppliers" from mytable;
"""
# Create connection to SQLite database
conn2 = sqlite3.connect('mydatabase.db')

result2 = pd.read_sql_query(sql_query, conn1)

# Show the result
result2.head()

   Number of col suppliers
0                        1

In [ ]:
#we try and  get how many types of locations available in our columbus dataset
#Query data from SQLite database using SQL

sql_query = """
SELECT COUNT( DISTINCT location) AS "Number of col locations" from mytable;
"""
# Create connection to SQLite database
conn3 = sqlite3.connect('mydatabase.db')

result3 = pd.read_sql_query(sql_query, conn1)

# Show the result
result3.head()

   Number of col locations
0                        7

In [ ]:
#we try and get the number of parking vacancies available in the 7 distinct parking locations
# Query data from SQLite database using SQL
sql_query = """
SELECT duration,zone,location,
COUNT(*) as total_parkings_per_location FROM mytable GROUP BY location ORDER BY total_parkings_per_location DESC LIMIT 18;
"""
result4= pd.read_sql_query(sql_query, conn1)
# Show the result
result4

   duration   zone                     location  total_parkings_per_location
0   2:19:15   1002  Short North Mobile Pay Only                       248964
1   2:59:59  31024          Short North Metered                       163945
2   0:40:00  45003               Arena District                        11076
3   1:53:06  25006                    Grandview                         5727
4   3:00:00  51007             Brewery District                         4265
5   0:30:00  17003                     Downtown                          460
6  23:59:59   9001           Childrens Hospital                           25

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in short north mobilepay" from mytable
WHERE location="Short North Mobile Pay Only";
"""

result5 = pd.read_sql_query(sql_query, conn1)

# Show the result
result5.head()

   zones in short north mobilepay
0                              45

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in short north metered" from mytable
WHERE location="Short North Metered";
"""
result6 = pd.read_sql_query(sql_query, conn1)

# Show the result
result6.head()

   zones in short north metered
0                            84

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in Arena" from mytable
WHERE location="Arena District";
"""
result7 = pd.read_sql_query(sql_query, conn1)

# Show the result
result7.head()

   zones in Arena
0               6

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in Grandview" from mytable
WHERE location="Grandview";
"""
result8 = pd.read_sql_query(sql_query, conn1)

# Show the result
result8.head()

   zones in Grandview
0                   6

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in Brewery District" from mytable
WHERE location="Brewery District";
"""
result9 = pd.read_sql_query(sql_query, conn1)

# Show the result
result9.head()

   zones in Brewery District
0                         35

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in Downtown District" from mytable
WHERE location="Downtown";
"""
result10 = pd.read_sql_query(sql_query, conn1)

# Show the result
result10.head()

   zones in Downtown District
0                           2

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228
sql_query = """
SELECT COUNT( DISTINCT zone ) AS "zones in Childrens Hospital" from mytable
WHERE location="Childrens Hospital";
"""
result11 = pd.read_sql_query(sql_query, conn1)

# Show the result
result11.head()

   zones in Childrens Hospital
0                            1

In [ ]:
#we then check which locations have low duration periods

sql_query = """
SELECT 	location,supplier,SUM(DISTINCT duration)  as Total_duration FROM mytable
GROUP BY location
ORDER BY 	Total_duration ASC;

"""

result12= pd.read_sql_query(sql_query, conn1)
# Show the result
result12.head()

             location  supplier  Total_duration
0  Childrens Hospital  Columbus            23.0
1            Downtown  Columbus           290.0
2           Grandview  Columbus           517.0
3    Brewery District  Columbus           884.0
4      Arena District  Columbus          2656.0

In [ ]:
#we then check which locations have low duration periods

sql_query = """
SELECT 	location,supplier,SUM(DISTINCT duration)  as Total_duration FROM mytable
GROUP BY location
ORDER BY 	Total_duration DESC;

"""
result13= pd.read_sql_query(sql_query, conn1)
# Show the result
result13.head(3)

                      location  supplier  Total_duration
0          Short North Metered  Columbus         13145.0
1  Short North Mobile Pay Only  Columbus         10136.0
2               Arena District  Columbus          2656.0

In [ ]:
#we can also try and get the average parking time on village street streeet
sql_query = """

SELECT location, AVG(duration) AS "Average parking time " FROM mytable
GROUP BY location
ORDER BY 2 desc;

"""
result14= pd.read_sql_query(sql_query, conn1)
# Show the result
result14.head()

                      location  Average parking time
0           Childrens Hospital              23.000000
1                     Downtown               4.467391
2  Short North Mobile Pay Only               2.100063
3               Arena District               1.814012
4             Brewery District               1.701290

In [ ]:
#we can also try and get the average parking time on village street streeet
sql_query = """

SELECT location, AVG(duration) AS "Average parking time " FROM mytable
GROUP BY location
ORDER BY 2 asc;

"""
result15= pd.read_sql_query(sql_query, conn1)
# Show the result
result15.head(2)

              location  Average parking time
0  Short North Metered               1.165812
1            Grandview               1.231011

##Cleaning Data

In [ ]:
datak.tail(1)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,supplier,zone
434461,0:15:00,Short North Metered,2019-08-21 21:24:00.000,2019-08-21 21:09:00.000,$0.50,2019-08-22 03:45:00.000,Columbus,31040

In [ ]:
#we drop all unnecessary columns,
#The only insignificant column is suppliers Since all our data is from columnbus we wont need it in our analysis
#Also our data is already really clean and petite

datak.drop(columns=["supplier"] ,axis=1, inplace=True)

In [ ]:
#we dont have any null values to drop so we recheck
# using dropna() function
datak.isna().sum()

duration              0
location              0
parking_end_date      0
parking_start_date    0
parkingamount         0
paymentdate           0
zone                  0
dtype: int64

In [ ]:
#since the data is mostly clean we finish by changing all the date columns from"object"to"date"
#convert column to datetime pandas
datak['paymentdate'] = pd.to_datetime(datak['paymentdate'])

In [ ]:
#since the data is mostly clean we finish by changing all the date columns from"object"to"date"
#convert column to datetime pandas
datak['parking_end_date'] = pd.to_datetime(datak['parking_end_date'])

In [ ]:
#since the data is mostly clean we finish by changing all the date columns from"object"to"date"
#convert column to datetime pandas
datak['parking_start_date'] = pd.to_datetime(datak['parking_start_date'])

In [ ]:
import pandas as pd

# the column'duration' that contains object data we will change it to timedelta datatype
#The function automatically infers the appropriate format of the duration based on the values in the column.
#It can handle various formats such as 'days', 'hours:minutes:seconds', or 'hours'.

# Convert the 'duration' column to timedelta
# Convert the 'duration' column to minutes
datak['duration'] = pd.to_timedelta(datak['duration']).dt.total_seconds() / 60
datak['duration'] = datak['duration'].astype(int)

In [ ]:
import pandas as pd

# Assuming you have a DataFrame called 'df' with a column named 'payment' that contains dollar sign and numeric data

# Remove dollar sign and convert column to numeric type
datak['parkingamount'] = datak['parkingamount'].str.replace('$', '').astype(float)

# Convert column to integer
datak['parkingamount'] = datak['parkingamount'].astype(int)

In [ ]:
datak.dtypes

duration                       int64
location                      object
parking_end_date      datetime64[ns]
parking_start_date    datetime64[ns]
parkingamount                  int64
paymentdate           datetime64[ns]
zone                           int64
dtype: object

##Normality ,Homogenity and Stationarity tests

## Feature Engineering Temporal Variables

In [ ]:
datak.head(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,zone
0,139,Short North Mobile Pay Only,2019-02-22 21:59:00,2019-02-22 19:40:00,7,2019-02-22 19:40:00,1002
1,120,Short North Mobile Pay Only,2019-04-05 19:18:00,2019-04-05 17:18:00,6,2019-04-05 17:19:00,2007

In [ ]:
import datetime

# Create a new column called "day_of_week".
datak["day_of_week"] = datak["parking_start_date"].dt.weekday

# Filter the data so that only the days from 1 to 7 are included.
datak = datak[datak["day_of_week"].isin([0, 1, 2, 3, 4, 5, 6])]

# Print the DataFrame.
(datak.head(2))

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,zone,day_of_week
0,139,Short North Mobile Pay Only,2019-02-22 21:59:00,2019-02-22 19:40:00,7,2019-02-22 19:40:00,1002,4
1,120,Short North Mobile Pay Only,2019-04-05 19:18:00,2019-04-05 17:18:00,6,2019-04-05 17:19:00,2007,4

In [ ]:
# Map the days of the week to their actual names.
day_of_week_map = {
    0: "Monday",
    1: "Tuesday",
    2: "Wednesday",
    3: "Thursday",
    4: "Friday",
    5: "Saturday",
    6: "Sunday"
}
datak["day_of_week"] = datak["day_of_week"].apply(lambda day_of_week: day_of_week_map[day_of_week])

# Inspect the DataFrame to make sure that the day_of_week column is correct.
print(datak.head(2))

   duration                     location    parking_end_date  \
0       139  Short North Mobile Pay Only 2019-02-22 21:59:00
1       120  Short North Mobile Pay Only 2019-04-05 19:18:00

   parking_start_date  parkingamount         paymentdate  zone day_of_week
0 2019-02-22 19:40:00              7 2019-02-22 19:40:00  1002      Friday
1 2019-04-05 17:18:00              6 2019-04-05 17:19:00  2007      Friday

In [ ]:
datak['day_type'] = datak['day_of_week'].apply(lambda x: 'Weekend' if x in ['Saturday','Sunday'] else 'Weekday')

In [ ]:
datak['parking_hour'] = datak['parking_start_date'].dt.hour
datak['time_of_day'] = datak['parking_hour'].apply(lambda x: 'Morning' if x < 12 else ('Afternoon' if x < 18 else 'Evening'))

In [ ]:
import pandas as pd
import datetime

def _get_season(parking_start_date):
    month = parking_start_date.month
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

# Create a new column for seasons.
datak["season"] = datak["parking_start_date"].apply(lambda parking_start_date: _get_season(parking_start_date))

# Inspect the DataFrame to make sure that the season column is correct.
datak.head(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,zone,day_of_week,day_type,parking_hour,time_of_day,season
0,139,Short North Mobile Pay Only,2019-02-22 21:59:00,2019-02-22 19:40:00,7,2019-02-22 19:40:00,1002,Friday,Weekday,19,Evening,Winter
1,120,Short North Mobile Pay Only,2019-04-05 19:18:00,2019-04-05 17:18:00,6,2019-04-05 17:19:00,2007,Friday,Weekday,17,Afternoon,Spring

In [ ]:
import pandas as pd
import holidays

In [ ]:
# Fetch public holidays for Ohio, USA
ohio_holidays = holidays.US(years=2019, state='OH')

In [ ]:
# Create a new column called "public_holiday".
datak["public_holiday"] = 0

In [ ]:
# Fill the new column with the public holidays for the Aus.
for index, row in datak.iterrows():
    date = row['parking_start_date']
    if date in ohio_holidays:
        datak.loc[index, "public_holiday"] = 1

In [ ]:
import pandas as pd

#check if the ohio holidays has taken up we change it to categorical and test it
# Convert the column to a categorical data type
datak['public_holiday'] = datak['public_holiday'].astype('category')

# Check if the column is categorical
is_categorical = datak['public_holiday'].dtype.name == 'category'

if is_categorical:
    print("The column is categorical")
else:
    print("The column is not categorical")

The column is categorical

In [ ]:
datak.head(2)

,duration,location,parking_end_date,parking_start_date,parkingamount,paymentdate,zone,day_of_week,day_type,parking_hour,time_of_day,season,public_holiday
0,139,Short North Mobile Pay Only,2019-02-22 21:59:00,2019-02-22 19:40:00,7,2019-02-22 19:40:00,1002,Friday,Weekday,19,Evening,Winter,0
1,120,Short North Mobile Pay Only,2019-04-05 19:18:00,2019-04-05 17:18:00,6,2019-04-05 17:19:00,2007,Friday,Weekday,17,Afternoon,Spring,0

In [ ]:
datak.dtypes

duration                       int64
location                      object
parking_end_date      datetime64[ns]
parking_start_date    datetime64[ns]
parkingamount                  int64
paymentdate           datetime64[ns]
zone                           int64
day_of_week                   object
day_type                      object
parking_hour                   int32
time_of_day                   object
season                        object
public_holiday              category
dtype: object