<a href="https://colab.research.google.com/github/Eswa2020/Data-analysis-and-wrangling-various-projects/blob/master/PARKING_SYSTEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing libraries and loading dataset

In [2]:
#importimg our libraries to use
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime
%matplotlib inline

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
#let's load the  dataset 
dataq=pd.read_csv("/content/drive/MyDrive/melbourne_parking_data.csv",encoding='ISO-8859-1')
dataq.head()

,DeviceId,ArrivalTime,DepartureTime,DurationMinutes,StreetMarker,SignPlateID,Sign,AreaName,StreetId,StreetName,BetweenStreet1ID,BetweenStreet1,BetweenStreet2ID,BetweenStreet2,SideOfStreet,SideOfStreetCode,SideName,BayId,InViolation,VehiclePresent
0,17176,02/15/2019 07:45:29 PM,02/15/2019 07:46:52 PM,1,13009S,NaN,NaN,Docklands,528,COLLINS STREET,1285,SPENCER STREET,79,BATMANS HILL DRIVE,4,S,South,6005,False,True
1,17176,03/25/2019 08:35:40 PM,03/25/2019 08:39:08 PM,4,13009S,NaN,NaN,Docklands,528,COLLINS STREET,1285,SPENCER STREET,79,BATMANS HILL DRIVE,4,S,South,6005,False,True
2,17176,01/17/2019 05:28:55 AM,01/17/2019 06:57:09 AM,89,13009S,NaN,NaN,Docklands,528,COLLINS STREET,1285,SPENCER STREET,79,BATMANS HILL DRIVE,4,S,South,6005,False,True
3,17176,03/13/2019 10:18:17 PM,03/13/2019 10:18:24 PM,0,13009S,NaN,NaN,Docklands,528,COLLINS STREET,1285,SPENCER STREET,79,BATMANS HILL DRIVE,4,S,South,6005,False,False
4,17176,01/18/2019 06:04:37 AM,01/18/2019 06:07:29 AM,3,13009S,NaN,NaN,Docklands,528,COLLINS STREET,1285,SPENCER STREET,79,BATMANS HILL DRIVE,4,S,South,6005,False,True

In [5]:
dataq.tail()

,DeviceId,ArrivalTime,DepartureTime,DurationMinutes,StreetMarker,SignPlateID,Sign,AreaName,StreetId,StreetName,BetweenStreet1ID,BetweenStreet1,BetweenStreet2ID,BetweenStreet2,SideOfStreet,SideOfStreetCode,SideName,BayId,InViolation,VehiclePresent
1048570,17419,01/21/2019 07:17:38 AM,01/21/2019 07:30:00 AM,13,13398E,NaN,NaN,Docklands,79,BATMANS HILL DRIVE,1457,FISHPLATE LANE,528,COLLINS STREET,2,E,East,6656,False,True
1048571,17418,11/18/2019 10:05:57 PM,11/18/2019 10:07:31 PM,2,13397W,NaN,NaN,Docklands,1383,VILLAGE STREET,131,BRENTANI WAY,974,MCCRAE STREET,5,W,West,6320,False,False
1048572,17420,06/13/2019 09:30:00 AM,06/13/2019 10:02:23 AM,32,13399W,99.0,2P MTR M-F 9:30-16:00,Docklands,1383,VILLAGE STREET,131,BRENTANI WAY,974,MCCRAE STREET,5,W,West,6321,False,True
1048573,17418,05/15/2019 04:31:54 PM,05/15/2019 04:32:56 PM,1,13397W,430.0,1/4P M-F 16:00-18:30,Docklands,1383,VILLAGE STREET,131,BRENTANI WAY,974,MCCRAE STREET,5,W,West,6320,False,False
1048574,17418,05/25/2019 06:10:25 PM,05/25/2019 06:18:14 PM,8,13397W,362.0,1P SAT-SUN 7:30-18:30,Docklands,1383,VILLAGE STREET,131,BRENTANI WAY,974,MCCRAE STREET,5,W,West,6320,False,True

## Exploring our dataset

In [6]:
dataq.shape

(1048575, 20)

In [7]:
dataq.isna().sum()

DeviceId                 0
ArrivalTime              0
DepartureTime            0
DurationMinutes          0
StreetMarker             0
SignPlateID         286382
Sign                286382
AreaName                 1
StreetId                 0
StreetName               0
BetweenStreet1ID         0
BetweenStreet1           0
BetweenStreet2ID         0
BetweenStreet2           0
SideOfStreet             0
SideOfStreetCode         0
SideName                 0
BayId                    0
InViolation              0
VehiclePresent           0
dtype: int64

In [14]:
dataq.duplicated().sum()

407

In [15]:
dataq.dtypes

DeviceId              int64
ArrivalTime          object
DepartureTime        object
DurationMinutes       int64
StreetMarker         object
SignPlateID         float64
Sign                 object
AreaName             object
StreetId              int64
StreetName           object
BetweenStreet1ID      int64
BetweenStreet1       object
BetweenStreet2ID      int64
BetweenStreet2       object
SideOfStreet          int64
SideOfStreetCode     object
SideName             object
BayId                 int64
InViolation            bool
VehiclePresent         bool
dtype: object

In [9]:
dataq.info

<bound method DataFrame.info of          DeviceId             ArrivalTime           DepartureTime  \
0           17176  02/15/2019 07:45:29 PM  02/15/2019 07:46:52 PM
1           17176  03/25/2019 08:35:40 PM  03/25/2019 08:39:08 PM
2           17176  01/17/2019 05:28:55 AM  01/17/2019 06:57:09 AM
3           17176  03/13/2019 10:18:17 PM  03/13/2019 10:18:24 PM
4           17176  01/18/2019 06:04:37 AM  01/18/2019 06:07:29 AM
...           ...                     ...                     ...
1048570     17419  01/21/2019 07:17:38 AM  01/21/2019 07:30:00 AM
1048571     17418  11/18/2019 10:05:57 PM  11/18/2019 10:07:31 PM
1048572     17420  06/13/2019 09:30:00 AM  06/13/2019 10:02:23 AM
1048573     17418  05/15/2019 04:31:54 PM  05/15/2019 04:32:56 PM
1048574     17418  05/25/2019 06:10:25 PM  05/25/2019 06:18:14 PM

         DurationMinutes StreetMarker  SignPlateID                   Sign  \
0                      1       13009S          NaN                    NaN
1                      4       13009S          NaN                    NaN
2                     89       13009S          NaN                    NaN
3                      0       13009S          NaN                    NaN
4                      3       13009S          NaN                    NaN
...                  ...          ...          ...                    ...
1048570               13       13398E          NaN                    NaN
1048571                2       13397W          NaN                    NaN
1048572               32       13399W         99.0  2P MTR M-F 9:30-16:00
1048573                1       13397W        430.0   1/4P M-F 16:00-18:30
1048574                8       13397W        362.0  1P SAT-SUN 7:30-18:30

          AreaName  StreetId          StreetName  BetweenStreet1ID  \
0        Docklands       528      COLLINS STREET              1285
1        Docklands       528      COLLINS STREET              1285
2        Docklands       528      COLLINS STREET              1285
3        Docklands       528      COLLINS STREET              1285
4        Docklands       528      COLLINS STREET              1285
...            ...       ...                 ...               ...
1048570  Docklands        79  BATMANS HILL DRIVE              1457
1048571  Docklands      1383      VILLAGE STREET               131
1048572  Docklands      1383      VILLAGE STREET               131
1048573  Docklands      1383      VILLAGE STREET               131
1048574  Docklands      1383      VILLAGE STREET               131

         BetweenStreet1  BetweenStreet2ID      BetweenStreet2  SideOfStreet  \
0        SPENCER STREET                79  BATMANS HILL DRIVE             4
1        SPENCER STREET                79  BATMANS HILL DRIVE             4
2        SPENCER STREET                79  BATMANS HILL DRIVE             4
3        SPENCER STREET                79  BATMANS HILL DRIVE             4
4        SPENCER STREET                79  BATMANS HILL DRIVE             4
...                 ...               ...                 ...           ...
1048570  FISHPLATE LANE               528      COLLINS STREET             2
1048571    BRENTANI WAY               974       MCCRAE STREET             5
1048572    BRENTANI WAY               974       MCCRAE STREET             5
1048573    BRENTANI WAY               974       MCCRAE STREET             5
1048574    BRENTANI WAY               974       MCCRAE STREET             5

        SideOfStreetCode SideName  BayId  InViolation  VehiclePresent
0                      S    South   6005        False            True
1                      S    South   6005        False            True
2                      S    South   6005        False            True
3                      S    South   6005        False           False
4                      S    South   6005        False            True
...                  ...      ...    ...          ...             ...
1048570                E     East   6656        False            True
1048571                W     West   6320        False           False
1048572                W     West   6321        False            True
1048573                W     West   6320        False           False
1048574                W     West   6320        False            True

[1048575 rows x 20 columns]>

##Cleaning Data

**Class distribution**
First, let’s look at the frequency distribution by parking zones (see Figure 3). Unsurprisingly, Zone 1 was most common since we would always try to find a parking space closest to my apartment block. The distribution also suggests a class imbalance, something to take into consideration when building and evaluating an ML model.

**Hour of the day**
Next, let’s look at the percentage of parking sessions across different hours of the day by parking zones (see Figure 4). The later I returned home, the more unlikely it was to find parking space in Zone 1. This was common sense, but it was good to know that the data I collected validated this observation. Based on Figure 4, it also appeared that hour could be a useful feature in predicting parking availability.

**Day of the week**
I also asked myself, “Are there certain days of the week where it is less probable to find a parking space in Zone 1?” Based on the data collected, yes! The probability of getting a parking space in Zone 1 was the highest on Mondays (~83%), decreased over the week days and was the lowest on Thursdays (~59%) and Sundays (~61%). Thus, day_of_week could also be a useful predictor for parking availability.

**Public holiday, eve, or neither?**
Through out the data collection period, it felt like it was harder to find a parking space in Zone 1 on public holidays. I guessed it was because the next day could be a working/schooling day and residents tend to stay home. The opposite was true for public holiday eves, meaning residents might not return home early since the next day was a public holiday.

In [ ]:
#since the data is mostly clean we start with changing the date column from"object"to"date"
#convert column to datetime pandas
dataq['ArrivalTime'] = pd.to_datetime(dataq['ArrivalTime'])

In [ ]:
#since the data is mostly clean we start with changing the date column from"object"to"date"
#convert column to datetime pandas
dataq['DepartureTime'] = pd.to_datetime(dataq['DepartureTime'])

In [ ]:
dataq.dtypes

In [ ]:
#we drop all unnecessary columns,we first drop signplateID Since we wont need it in our analysis
#also we drop all other primary key columns sinceon eis enough
#SignPlateID ,StreetId,BayId 

dataq.drop(columns=["Sign","SignPlateID","BetweenStreet1","BetweenStreet2","BetweenStreet1ID","BetweenStreet2ID"] ,axis=1, inplace=True)

In [ ]:
dataq.drop(columns=["StreetId","StreetMarker","SideOfStreet","SideOfStreetCode","SideName"] ,axis=1, inplace=True)

In [ ]:
#also drop all the null values
# using dropna() function  
dataq.dropna()
dataq.head()

In [ ]:
dataq.isna().sum()

In [ ]:
print(dataq.columns.tolist())

In [ ]:
#Exctract month and create a dedicated column df["Month"] from a 
#column in datetime format df["Date"]
dataq['Month'] = pd.DatetimeIndex(dataq['ArrivalTime']).month

In [ ]:
#Exctract month and create a dedicated column df["Month"] from a 
#column in datetime format df["Date"]
dataq['Year'] = pd.DatetimeIndex(dataq['ArrivalTime']).year

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['Day'] = pd.DatetimeIndex(dataq['DepartureTime']).day

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['hourarrive'] = pd.DatetimeIndex(dataq['ArrivalTime']).hour

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['secondarrive'] = pd.DatetimeIndex(dataq['ArrivalTime']).second

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['minutearrive'] = pd.DatetimeIndex(dataq['ArrivalTime']).minute

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['seconddepart'] = pd.DatetimeIndex(dataq['DepartureTime']).second

In [ ]:
#Exctract day and create a dedicated column df["Day"] from a 
#column in datetime format df["Date"]
dataq['minutedepart'] = pd.DatetimeIndex(dataq['DepartureTime']).minute

In [ ]:

print(dataq.columns.tolist())

##In-depth exploration using SQL

In [ ]:
!pip install pandas
!pip install sqlalchemy

In [ ]:
import sqlite3
from sqlalchemy import create_engine

# connect to the database
conn = sqlite3.connect('example.db')

# create engine
engine = create_engine('sqlite:///example.db')

In [ ]:
#load the sql into our  environment
%load_ext sql

In [ ]:
#connect to our memory sqlite database
%sql sqlite://

In [ ]:
#we first convert our database into csv so that we can run in the  sql environment
# converting to CSV file
dataq3=dataq.to_csv('raw_data.csv', index=False)

In [ ]:
#importimg our libraries to use
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime
%matplotlib inline

In [ ]:
# connect to the database
conn = sqlite3.connect('example.db')

# create engine
engine = create_engine('sqlite:///example.db')

In [ ]:
!add-apt-repository -y ppa:sergey-dryabzhinsky/packages
!apt update
!apt install sqlite3

In [ ]:
import sqlite3
print(sqlite3.sqlite_version) # 3.33.0

In [ ]:
import sqlite3
import pandas as pd

# Load data from CSV file into a Pandas DataFrame
with open('raw_data.csv', 'r') as f:
    data = pd.read_csv(f, index_col=0, encoding='utf-8')

# Create a connection to a SQLite database
conn = sqlite3.connect('mydatabase.db')

# Write the DataFrame to a SQLite table
data.to_sql('dataq', conn)

# Execute SQL commands on the SQLite table
cursor = conn.cursor()
cursor.execute('SELECT * FROM dataq3 LIMIT 5;')
result = cursor.fetchall()
print(result)

# Close the database connection
conn.close()

In [ ]:
import sqlite3

# Read data into pandas DataFrame
with open('raw_data.csv', 'r') as f:
    data = pd.read_csv(f, index_col=0, encoding='utf-8')

# Create connection to SQLite database
conn = sqlite3.connect('mydatabase.db')

# Write DataFrame to SQLite database
data.to_sql('mytable', conn)

# Query data from SQLite database using SQL
sql_query = """
SELECT * FROM mytable LIMIT 5;
"""

result = pd.read_sql_query(sql_query, conn)

# Close connection to SQLite database
conn.close()

# Show the result
result.head()

In [ ]:
#we try and get the number of parking stations serving melnbourne city we can also determine if we will use a single or a multi server queue system
#Query data from SQLite database using SQL

sql_query = """
SELECT COUNT( DISTINCT DeviceId ) AS "Number of melb servers" from mytable;
"""
# Create connection to SQLite database
conn1 = sqlite3.connect('mydatabase.db')

result1 = pd.read_sql_query(sql_query, conn1)

# Show the result
result1.head()

In [ ]:
#We first get the total tarnsactions this also transalates to number of customers served our devices have
# Create  another to use connection to SQLite database
conn1 = sqlite3.connect('mydatabase.db')

# Query data from SQLite database using SQL
sql_query = """
SELECT COUNT(DeviceId) AS "Number of melb customers"  FROM mytable;
"""

result3 = pd.read_sql_query(sql_query, conn1)


# Show the result
result3.head()

In [ ]:
#we try and get the number of areanames that melbourne parking service facilaitates
# Create connection to SQLite database
conn1 = sqlite3.connect('mydatabase.db')
# Query data from SQLite database using SQL
sql_query = """
SELECT COUNT( DISTINCT AreaName ) AS "Number of Areanames" FROM mytable;
"""
result5= pd.read_sql_query(sql_query, conn1)
# Show the result
result5.head()

In [ ]:
#we try and get the number of streetnames that melbourne parking service facilaitates
# Query data from SQLite database using SQL
sql_query = """
SELECT COUNT( DISTINCT StreetName ) AS "streets of melbourne" FROM mytable;
"""
result5= pd.read_sql_query(sql_query, conn1)
# Show the result
result5.head()

In [ ]:
#we try and get the number of streetnames that melbourne parking service facilaitates
# Query data from SQLite database using SQL
sql_query = """
SELECT DeviceId,StreetName,AreaName, COUNT(*) as transactions_per_area FROM mytable GROUP BY AreaName ORDER BY transactions_per_area DESC LIMIT 18;
"""
result6= pd.read_sql_query(sql_query, conn1)
# Show the result
result6

In [ ]:
#we also check which device has been used the most in each area and  docklands server 17418 seems to take the fair share of the transactions
sql_query = """

SELECT DeviceId,StreetName,AreaName,hourarrive, COUNT(*) as transactions_per_area FROM mytable GROUP BY AreaName ORDER BY transactions_per_area desc LIMIT 18;
"""
result7= pd.read_sql_query(sql_query, conn1)
# Show the result
result7.head()

In [ ]:
#we go ahead and determine number of servers in docklands
#we then get the how many servers docklands has and it has 228 
sql_query = """
SELECT COUNT( DISTINCT DeviceId ) AS "Number of docks servers" from mytable
WHERE AreaName="Docklands";
"""
# Create connection to SQLite database
conn1 = sqlite3.connect('mydatabase.db')

result7b = pd.read_sql_query(sql_query, conn1)

# Show the result
result7b.head()

In [ ]:
#we also go ahead and get the number of transactions/customers
#docklands has over 95% of transactions in our database
# Query data from SQLite database using SQL
sql_query = """
SELECT COUNT(DeviceId) AS "Number of dock customers"  FROM mytable
WHERE AreaName="Docklands";
"""
result7c = pd.read_sql_query(sql_query, conn1)
# Show the result
result7c.head()

In [ ]:
#we can also try and get the average parking time on collins streeet
sql_query = """

SELECT AVG(DurationMinutes ) AS "Average parking time in docklands" FROM mytable
WHERE AreaName="Docklands";

"""
result7d= pd.read_sql_query(sql_query, conn1)
# Show the result
result7d.head()

In [ ]:
#we then check which areanames have high duration periods

sql_query = """
SELECT 	DeviceId,AreaName,COUNT(DISTINCT DurationMinutes)  as duration FROM mytable
GROUP BY AreaName
ORDER BY 	duration DESC
LIMIT 10;

"""
result9= pd.read_sql_query(sql_query, conn1)
# Show the result
result9.head()

In [ ]:
#we then check which areanames have low duration periods

sql_query = """
SELECT 	DeviceId,AreaName,COUNT(DISTINCT DurationMinutes)  as duration FROM mytable
GROUP BY AreaName
ORDER BY 	duration ASC
LIMIT 10;

"""

result10= pd.read_sql_query(sql_query, conn1)
# Show the result
result10.head()

In [ ]:
#we explore docklands futrther cause it is biased  and has 99% of the transactions we first  explore the number of stations in each area and dockalnads has most stations 228
sql_query = """


SELECT DeviceId,AreaName,DurationMinutes,StreetName,BayId,VehiclePresent,Month,Day,hourarrive
FROM mytable
WHERE AreaName ='Docklands';

"""

result11= pd.read_sql_query(sql_query, conn1)
# Show the result
result11.head()

In [ ]:
#we explore docklands futrther cause it is biased  and has 99% of the transactions we first  explore the number
# servers that are busiest and are in which streets
sql_query = """

SELECT StreetName,DeviceId, COUNT(*) FROM mytable
GROUP BY DeviceId
ORDER BY 3 desc
LIMIT 18;

"""

result12= pd.read_sql_query(sql_query, conn1)
# Show the result
result12.head()

In [ ]:
#we explore docklands futrther cause it is biased  and has 99% of the transactions we first  explore the 
#servers that are least busiest
sql_query = """

SELECT StreetName, COUNT(*) FROM mytable
GROUP BY DeviceId
ORDER BY 2 asc
LIMIT 18;

"""

result12v= pd.read_sql_query(sql_query, conn1)
# Show the result
result12v.head()

In [ ]:
#we check which street has the highest number of duration minutes seems it is collins street  
sql_query = """

SELECT *
FROM mytable
ORDER BY DurationMinutes desc
LIMIT 20;

"""

result14= pd.read_sql_query(sql_query, conn1)
# Show the result
result14.head()

In [ ]:
# We check specifically the server with most transactions in docklands 
#sever 17195 we discover that its in COLLIN street with bayid=6005
sql_query = """

SELECT *
FROM mytable
WHERE DeviceId ="17195" 
ORDER BY 3 DESC
LIMIT 10;

"""
result15= pd.read_sql_query(sql_query, conn1)
# Show the result
result15.head()

In [ ]:
#we go ahead and investigate the streetnames in docklands that have duration times of more than 1000 and has a vehicle present
#Most vehicles that have the longest duration are packed at midnight
#colllins street seems to be most affected 
#and most vehicles are parked in the month of october
sql_query = """

SELECT DeviceId,ArrivalTime,DurationMinutes,AreaName,StreetName,VehiclePresent
FROM mytable
WHERE DurationMinutes >"1000" AND VehiclePresent="1"
ORDER BY 3 desc
LIMIT 10;


"""
result17= pd.read_sql_query(sql_query, conn1)
# Show the result
result17.head()

In [ ]:
#we try and get the number of parking bays on collins street
sql_query = """

SELECT COUNT( DISTINCT BayID ) AS "Number of bays in collins" FROM mytable
WHERE StreetName="COLLINS STREET";

"""
result18= pd.read_sql_query(sql_query, conn1)
# Show the result
result18.head()

In [ ]:
#we go ahead and investigate collins street
sql_query = """

SELECT *
FROM mytable
WHERE StreetName="COLLINS STREET"
ORDER BY 3 DESC
LIMIT 10;

"""
result19= pd.read_sql_query(sql_query, conn1)
# Show the result
result19.head()

In [ ]:
#we can also try and get number of servers serving collins street
sql_query = """

SELECT COUNT( DISTINCT DeviceId ) AS "Number of servers in collins" FROM mytable
WHERE StreetName="COLLINS STREET";

"""
result20= pd.read_sql_query(sql_query, conn1)
# Show the result
result20.head()

In [ ]:
#we can also try and get the average parking time on collins streeet
sql_query = """

SELECT AVG(DurationMinutes ) AS "Average parking time in collins" FROM mytable
WHERE StreetName="COLLINS STREET";

"""
result21= pd.read_sql_query(sql_query, conn1)
# Show the result
result21.head()

In [ ]:
#we can do the same for village street which holds the server with highest number of transactions
sql_query = """

SELECT COUNT( DISTINCT BayID ) AS "Number of bays in village" FROM mytable
WHERE StreetName="VILLAGE STREET";

"""
result22= pd.read_sql_query(sql_query, conn1)
# Show the result
result22.head()

In [ ]:
#we can also try and get the average parking time on village street streeet
sql_query = """

SELECT AVG(DurationMinutes ) AS "Average parking time in village" FROM mytable
WHERE StreetName="VILLAGE STREET";

"""
result23= pd.read_sql_query(sql_query, conn1)
# Show the result
result23.head()

From the above its an indication that we our model can only follow multiserver model queing system since most most the cars(90& and above) the parking station in the docklands.
Multiserver queue system must hab other characteristics
 
 All the parking stations are assumed to work at the identical capacity.

*   The arrival of cars follows the poisson distribution 
 
*   Parking stations service follows the exponential distribution.

*  All the parking stations are assumed to work at the identical capacity.

##Data Analysis

vehicle present indicates whether a car is present or not we first analyse car presence analysis and percentage

In [ ]:
import pandas as pd

# Load parking data into a DataFrame
#data = dataq
# Analyze the column indicating car presence
car_presence_counts = data["VehiclePresent"].value_counts()

# Calculate car presence percentage
car_presence_percentage = car_presence_counts / len(data) * 100

# Print the analysis results
print("Car Presence Analysis:")
print(car_presence_counts)
print("\nCar Presence Percentage:")
print(car_presence_percentage)

Create a bar plot to visualize the car presence for different months:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#Group the data by month and calculate the car presence counts for each month
car_presence_counts = dataq.groupby("Month")["VehiclePresent"].sum()

In [ ]:
#Create a bar plot to visualize the car presence for different months
plt.bar(car_presence_counts.index, car_presence_counts.values)
plt.xlabel("Month")
plt.ylabel("Vehicle Presence")
plt.title("Car Presence by Month")
plt.xticks(range(1, 13))  # Assuming the months are represented by numbers 1-12
plt.show()

In [ ]:
dataq.head()

In [ ]:
#import important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [ ]:
#Pivot the data to create a matrix where each row represents a day
#each column represents an hour, and the values represent the parking occupancy:
pivot_data = dataq.pivot_table(index="Month", columns="hourarrive", values="VehiclePresent", aggfunc=np.mean)

In [ ]:
#Perform clustering on the pivot data. Set the number of clusters and fit the K-means clustering algorithm:
num_clusters = 4  # Choose the appropriate number of clusters
kmeans = KMeans(n_clusters=num_clusters, random_state=0)
kmeans.fit(pivot_data.values)
cluster_labels = kmeans.labels_

In [ ]:
#Plot the clustering results using a heatmap:
plt.figure(figsize=(10, 6))
plt.imshow(pivot_data.values, cmap="hot")
plt.colorbar(label="Occupancy")
plt.xticks(np.arange(24), np.arange(24))
plt.yticks(np.arange(12), ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])
plt.xlabel("Hour")
plt.ylabel("Month")
plt.title("Clustering of Parking Occupancy by Hour")
plt.show()

we have generated a heatmap plot where each cell represents the average parking occupancy for a specific hour in a specific month. The color intensity represents the occupancy level, and the clustering analysis is reflected in the patterns and clusters observed in the heatmap.

weekly aps curve plot

In [ ]:
#import important libraries
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#Extract the day of the week from the "timestamp" column and calculate the average occupancy for each day of the week:
data["day_of_week"] = dataq["ArrivalTime"].dt.day_of_week
weekly_occupancy = data.groupby("day_of_week")["VehiclePresent"].mean()

In [ ]:
#Create a weekly APS curve plot:
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

plt.plot(weekdays, weekly_occupancy)
plt.xlabel("Day of the Week")
plt.ylabel("Average Occupancy")
plt.title("Weekly APS Curve Analysis")
plt.show()

Create a bar plot to visualize the car presence for different days:

In [ ]:
#Group the data by month and calculate the car presence counts for each month
car_daily_counts = dataq.groupby("Day")["VehiclePresent"].sum()

In [ ]:
#Create a bar plot to visualize the car presence for different months
plt.bar(car_daily_counts.index, car_daily_counts.values)
plt.xlabel("Day")
plt.ylabel("Vehicle Presence")
plt.title("Daily car presence")
plt.xticks(range(1, 32))  # Assuming the days are represented by numbers 1-31
plt.show()

Create a bar plot to visualize the car presence for different days:

In [ ]:
#Group the data by duration and calculate the car presence counts for each duration:
car_presence_count3 = dataq.groupby("DurationMinutes")["VehiclePresent"].sum()
#Create a line plot to visualize the car presence for different duration times
plt.plot(car_presence_count3.index, car_presence_count3.values)
plt.xlabel("Duration in minutes")
plt.ylabel("car Presence")
plt.title("Car Presence by Duration")
plt.show()

daily and weekly occupancy rate

In [ ]:
#Extract the week of the year and hour of the day from the "timestamp" column:
data["week_of_year"] = dataq["ArrivalTime"].dt.week
data["hour_of_day"] = dataq["ArrivalTime"].dt.hour

In [ ]:
#Calculate the average occupancy for each week of the year and hour of the day:
weekly_hourly_occupancy = data.groupby(["week_of_year", "hour_of_day"])["VehiclePresent"].mean().unstack()
#Create a heatmap to visualize the weekly occupancy rates with hours during the day:
plt.figure(figsize=(12, 6))
sns.heatmap(weekly_hourly_occupancy, cmap="hot", linewidths=0.5, linecolor="white")
plt.xlabel("Hour of the Day")
plt.ylabel("Week of the Year")
plt.title("Weekly Occupancy Rates with Hours during the Day")
plt.show()

##Bivariate Analysis

# Feature Engineering for queuing model

** To calculate the arrival rate for a multi-server queuing model, you first need to determine the rate at which customers arrive at the system. This is often denoted as λ (lambda) and can be measured in units of customers per unit of time (e.g., customers per hour).

Once you have determined the arrival rate, you can use Little's Law to calculate the average number of customers in the system. Little's Law states that the average number of customers in a system (L) is equal to the arrival rate (λ) multiplied by the average time a customer spends in the system (W). This can be expressed mathematically as L = λW.

Once you know the average service time, you can use Little's Law to calculate the average time a customer spends in the system (W) as W = L / λ = 1 / (μ - λ), where μ is the average service rate across all servers

In summary, to calculate the arrival rate for a multi-server queuing model, you need to:

Determine the arrival rate (λ) of customers to the system.
Calculate the average service time (1/μ) across all servers.
Use Little's Law to calculate the average time a customer spends in the system (W).
Use the traffic intensity formula to calculate the traffic intensity (ρ).
Solve for λ using λ = ρ * μ * s.

**

---

###1.calculating lamba=arival rate(λ)

To calculate the arrival rate for a multi-server queuing model, you need to know the average number of customers arriving per unit time. This is typically denoted by λ (lambda) and is expressed in units of customers per time interval (e.g., per hour or per day).

And since our data is alot we will use per day interval so as to compare with other world cities.

To calculate the arrival rate, you can use various methods, such as historical data analysis, customer surveys, or statistical modeling. One common approach is to use a Poisson process, which assumes that customer arrivals occur randomly and independently of one another over time. In our case,the arrival rate is simply the mean number of arrivals per unit time, which can be estimated from our data.

Determine the average arrival rate per customer at each server. This can be calculated as below:

In our case you can calculate the average arrival rate by dividing the total number of customers by the time period.

In [ ]:
#the total number of customers we had already pre-determined in our analysis
total_cust=1048575
total_cust

In [ ]:
#our intervals is per mimutes since our duration time is in minutes and we need it for utlization factor
#our data is from jan to dec of 2019=12
#average  daily arrival rate 
aar=(1048575/365)
aar

In [ ]:
#from our daily arrival rate we covert that per minute rate
#∴ 1 1 Per Day = 0.000694444444444444 1 Per Minute
aver_at=aar*0.000694444444444444
aver_at

Note that the arrival rate is expressed in different time units, in our case its customers per minute since our duration column is in minutes this will make our analysis easier.

So,our arrival rate is 1.99  which is almost 2 customers per minute.

### 2.Determine the number of servers in the system.

Parking sensors can be considered as servers in a queuing model for parking prediction. In a queuing model, there are typically one or more servers that process requests from customers. In the case of parking prediction, the customers are vehicles looking for parking spaces, and the servers are the parking sensors that provide information about the availability of parking spaces.The queuing model can be used to predict the availability of parking spaces based on the number of sensors and the historical data collected by these sensors.

In [ ]:
#number of servers had been pre-determined in our analysis
servers=1144
servers

### 3.Calculating the mu=service time for @ server(μ)

To calculate the average service time per customer, you need to know the total time that all customers spent being served and the total number of customers served,in our case the total no of customers have already being pre_determined

we calculate  the by:

Average Service Time per Customer = Total Service Time / Total Number of Customers

Total Service Time spent being served = Service Time of Customer 1 + Service Time of Customer 2 + ... + Service Time of Customer n

Next, you need to count the total number of customers served:

Total Number of Customers = n

In [ ]:
#total service time will be the sum of the duration column of our data which is in minutes 
serv_t = sum(dataq['DurationMinutes'])
serv_t

In [ ]:
#to get the average time per customer we take the total service time and divide by total customers served which is already predetermined
avg_serv_t=(serv_t/total_cust)
avg_serv_t

So the average time customers are taking in our service or system is an average of 47.99 or approx 48minutes per customer

### 3.utilization factor

Calculate the utilization factor, which is the ratio of the average service time to the average inter-arrival time. This can be done using the following formula:

Utilization Factor = (Average Service Time) * (Number of Servers) / (Average Inter-arrival Time)

Calculate the arrival rate using the following formula:

Arrival Rate = Utilization Factor * Server Capacity

where Server Capacity is the maximum number of customers that can be served simultaneously by the system.

In [ ]:
#Finally to get our utilization factor
#we then get the arrival rateb which we have calculated above 
#server capacity=average service time per customer which we also have
#Factor=aver_at/server_capacity
#server_capacity=number of servers*average service time
server_capacity=servers*avg_serv_t
server_capacity

In [ ]:
Factor=aver_at/server_capacity
Factor

Once you have determined the arrival rate, you can use this information along with other parameters, such as the service rate, the number of servers, and the queue capacity, to analyze the performance of the system and make predictions about wait times, queue lengths, and other metrics explained below.

#Metrics of success for queuing model

Multi server queue has two or more service facility in parallel providing identical service. All the
customers in the waiting line can be served by more than one station. The arrival time and the service time
follow poison and exponential distribution.(FCFS queue model)

Once you have estimated the arrival rate, you can use it along with other system parameters to calculate key performance metrics, such as the average wait time in the queue, the average number of customers in the system, and the probability of the system being in different states (e.g., idle, busy, or overloaded)

These metrics can be used to evaluate the system's efficiency and identify areas for improvement.Overall, a successful multi-server queuing model should have high utilization, low queue length, short waiting times, fast service times, high throughput, and low abandonment rates.

We are going to analyse the following metrics for our system:

* Average waiting time: 

* Queue length: 

* Service utilization: 

* Throughput: 

* Resource utilization: 

* System capacity: 

* Service level: 

* Cost: 

Overall, the success of a multi-server queuing model will depend on how well it can balance these metrics to meet the needs of the customers and the business.

### 1.Average waiting time

This metric measures the average amount of time that customers have to wait in the queue before they are served. A shorter waiting time is generally considered to be better.

In [ ]:
#The average time a customer spends in the system, W, can be calculated as 1/(μ - λ/N).
#Wq, can be calculated as Wq = (ρ * W) / (1 - ρ), where W is the average time a customer spends in the system.
#The average time a customer spends in the system, W, can be calculated as 1/(μ - λ/N).
#average_waiting_time= 1/(μ - λ/N).
#average_waiting_time=1/(serv_tg-(arrival_rate/total_cust)
arrival_rate=aver_at
t=(arrival_rate/total_cust)
t

In [ ]:
y=serv_t-t
y

In [ ]:
avg_waiting_t=1/y
avg_waiting_t

this is a really small waiting time which indicates that our customer spend seconds in service

### 2.Queue length/Traffic Intensity(p=trafiic intensity(ρ))

This metric measures the number of customers waiting in the queue at any given time. A shorter queue length is generally considered to be better.

To calculate the queue length in a multi-server queue model with 1144 servers, we already know the arrival rate of customers and the service rate of each server.

The customers arrive randomly and independently, and that the service time at each server follows an exponential distribution with a mean of 1/mu, where mu is the service rate, the expected queue length can be approximated by the following formula:

ρ = λ / (μ * s), where s is the number of servers. For a stable system, the traffic intensity must be less than 1, so you can solve for λ as λ = ρ * μ * s.

In [ ]:
#we have already solved for lamba and mu 
#calaculating for p won be hard =lambda/(mu*server)
traf_int=aver_at/(avg_serv_t*servers)
traf_int

In [ ]:
#once we get our rho or tra_int in our case we use it to calculate the queue length as follows
#queue_length = (rho**2 + rho) / (1 - rho)
queue_length = (traf_int**2 + traf_int) / (1 - traf_int)
queue_length
print("The expected queue length is:", queue_length)

In this formula, rho is the traffic intensity of the system, which is the ratio of the arrival rate to the product of the number of servers and the service rate. The formula is based on the assumption that the queue length follows a Poisson distribution and that the arrival rate and service rate are constant.

NB:our system is stable since it's below 1

In [ ]:
#The utilization rate (ρ) is calculated using the following formula:
#ρ = λ/μ
#where ρ is the utilization rate, λ is the arrival rate, and μ is the service rate.
ut=aver_at/avg_serv_t
ut

The servers are idle most times as we can see the utilization rate is pretty low at 41.57%

### 3.Throughput
This metric measures the number of customers served per unit of time. A higher throughput indicates that the system is processing customers more quickly.

In [ ]:
#In a multiple server model, the throughput is the number of completed tasks per unit time
#using the number of servers n, you can calculate the throughput, which is given by:X = n * μ
#Where X is the throughput, n is the number of servers, and μ is the service rate of each server.
#Therefore, the formula to calculate the throughput in a multiple server model is:X = n * λ / (1 + (n-1) * (λ/μ))
#This formula takes into account the fact that in a multiple server model,
#tasks can be serviced simultaneously by multiple servers, which can increase the throughput.
tp=(servers*aver_at/(1+(servers-1))*(aver_at/avg_serv_t))
tp

It is important to note that the maximum achievable throughput is limited by the service rate of the servers. 

In other words, if the service rate of the servers is not high enough to keep up with the arrival rate of customers, the system will experience congestion and the throughput will be reduced.

In our case though the throughput is high with being above 82.93%,Its also important to note that its below 90% since the system is not been fully utilized,in other words there is a  reduction in the number of jobs that can be processed per unit time.

### 4.Resource Utilization

This metric measures the percentage of time that each server is in use. A higher resource utilization indicates that the servers are being used more efficiently.Resource utilization refers to the degree to which resources such as servers, facilities, or equipment are used to handle the demand for service. It is a measure of how much of the available resources are being utilized at any given time. Resource utilization is usually expressed as a percentage and is calculated as follows:

Resource Utilization = (Total time resources are in use) / (Total time resources are available) * 100%

In [ ]:
# Suppose we have data on the number of customers served and the time spent in service and queue for a service system over a period of time.
customers_served = total_cust
time_in_service =serv_t # in minutes
time_in_queue = avg_waiting_t # in minutes
total_time = time_in_service + time_in_queue # total time in the system

# Calculate resource utilization
resource_utilization = (time_in_service / total_time) * 100
print("Resource utilization:", resource_utilization)

### 5.Service utilization

This metric measures the percentage of time that each server is busy serving customers. A higher service utilization indicates that the servers are being used more efficiently.

Service utilization, on the other hand, refers to the degree to which the service system is being used to handle the demand for service. It is a measure of how much of the demand for service is being satisfied by the system at any given time. Service utilization is also usually expressed as a percentage and is calculated as follows:

Service Utilization = (Total time spent in service) / (Total time in the system) * 100%

In [ ]:
# Calculate service utilization
service_utilization = (time_in_service / total_time) *100
print("Service utilization:", service_utilization)

###6.System capacity
This metric measures the maximum number of customers that the system can handle at any given time. A higher system capacity indicates that the system can handle more customers and is more scalable.

Once we have these values, we can calculate the system capacity using the following formula:

C = (1 / mu) * rho

In [ ]:
# input values
arrival_rate = aver_at
service_rate = avg_serv_t

# calculate traffic intensity
rho = arrival_rate / service_rate

# calculate system capacity
capacity = (1 / service_rate) * rho

print("System Capacity:", capacity)

###7.Service level
This metric measures the percentage of customers who receive service within a certain amount of time. A higher service level indicates that customers are receiving timely service.

To calculate the service level in a multi-server queueing model, we need to first determine the system's response time distribution, which is the time it takes for a job to be processed from the moment it arrives in the system. This can be calculated by taking into account the arrival rate of jobs, the service time distribution, and the number of servers in the system.
The service level can be calculated using the following formula:

Service level = Probability (response time <= service level target)

Where the response time is the time it takes for a job to be processed from the moment it arrives in the system.

In [ ]:
#there are 1144 servers=servers
#we already have a predetermined arrival rate=aver_at
#Define the service time distribution, which is the distribution of time it takes to process a job.
#You can use a probability distribution function, in our case we already know its the exponential distribution,to model this parameter. 
#will take a sample,of the service time an exponential distribution with a mean of (1/λ),
#you can use the following code to define the distribution function:
#mean=10
mean=10
mean

import numpy as np

def service_time():
    return np.random.exponential(mean)
#This function returns a random value from the exponential distribution with a mean of 10  minutes

In [ ]:
#Define the response time distribution, which is the distribution of time it takes for a job to be processed from 
#the moment it enters the system. 
#This can be calculated by taking into account the arrival rate=aver_at of jobs, 
#the service time distribution, and the number of servers=servers in the system. 
#You can use the following code to define the response time distribution function:

def response_time(servers, aver_at, service_time):
    rho=traf_int
    response_time_mean = 1 / (servers * (1 - rho))
    return np.random.exponential(response_time_mean)

#This function returns a random value from the response time distribution based on the number of servers,
# arrival rate, and service time distribution.

In [ ]:
#Simulate the system for a certain number of iterations and calculate the service level.
# For example, you can simulate the system for 10,000 iterations and calculate the service level 
#for a target of 90% service level within 5 minutes using the following code:

num_servers = servers
arrival_rate =aver_at

def service_level(num_servers, arrival_rate, service_time, iterations=10000, target=5):
    completed_jobs = 0
    total_jobs = 0
    for i in range(iterations):
        total_jobs += 1
        if response_time(num_servers, arrival_rate, service_time) <= target:
            completed_jobs += 1
    return completed_jobs / total_jobs

print(service_level(num_servers, arrival_rate, service_time, iterations=20000, target=5))

#This code calculates the service level for a target of 90% within 5 minutes using 10,000 iterations of the simulation. 
#The output is the percentage of jobs that were completed within the target time frame.

###8.Cost
This metric measures the total cost of operating the queuing system, including the cost of servers, infrastructure, and staffing. It is an important metric for evaluating the profitability of the system

In [ ]:

import numpy as np

# Define system parameters which are already pre_deterined
num_servers = servers
arrival_rate = aver_at
service_time_mean = avg_serv_t

# Define costs all are current prices at 2023
server_cost = 136.58 # in unit cost of United States Dollar
job_cost = 500 #in unit cost of United States Dollar
wait_cost = 4 # in melbourne parking fee currently United States Dollar per hour

# Simulate the queuing model
time_frame = 60 # minutes in 1 hour
total_jobs = arrival_rate * time_frame
utilization_rate = arrival_rate * service_time_mean / num_servers
avg_jobs = utilization_rate / (1 - utilization_rate)
avg_waiting_time = avg_jobs / arrival_rate
avg_response_time = service_time_mean / (1 - utilization_rate)
server_cost_total = server_cost * num_servers * time_frame
job_cost_total = job_cost * total_jobs
wait_cost_total = wait_cost * avg_waiting_time * total_jobs
total_cost = server_cost_total + job_cost_total + wait_cost_total

# Print the results
print(f"Total cost in dollars: {total_cost}")

#Analysing the queue model/distribution of the model

To determine the distribution of a multiserver queuing model for over 1000 servers using Python, you will need to perform some statistical analysis on the data. Here are the steps you can follow:

* Collect data: Collect data on the arrival rate, service rate, and the number of servers in the system. You can use simulations or real-world data to collect this information.

* Analyze the data: Use statistical software in Python such as NumPy, SciPy, and Pandas to analyze the data. Calculate the mean, variance, and standard deviation of the data.

* Choose a distribution: Once you have analyzed the data, choose a probability distribution that best fits the data. There are several probability distributions to choose from, such as the Poisson distribution, the exponential distribution, or the normal distribution.

* Fit the distribution: Use the chosen probability distribution to fit the data. You can use Python libraries such as SciPy or Statsmodels to fit the distribution.

* Evaluate the model: Evaluate the goodness of fit of the model using statistical tests such as the Kolmogorov-Smirnov test or the Chi-Square test.

* Interpret the results: Once you have a model that fits the data well, you can use it to make predictions about the queuing system. You can use the model to estimate the average waiting time, the utilization rate of the servers, and other performance metrics.


Overall, analyzing a multiserver queuing model for over 1000 servers using Python can be complex and time-consuming. It may be useful to consult with a statistician or an expert in queuing theory to ensure that your analysis is accurate and reliable.

In [ ]:
import numpy as np

# Define the queuing model
arrival_rate = 5  # customers per minute
service_rate = 6  # customers per minute
num_servers = 1000

# Generate random arrivals and service times
arrival_times = np.cumsum(np.random.exponential(scale=1/arrival_rate, size=1000))
service_times = np.random.exponential(scale=1/service_rate, size=1000)

# Simulate the queuing system
num_customers = len(arrival_times)
servers = np.zeros(num_servers)
queue = []
wait_times = np.zeros(num_customers)
for i in range(num_customers):
    # Check for available servers
    available_servers = np.where(servers == 0)[0]
    if len(available_servers) > 0:
        # Assign customer to a server
        server_index = available_servers[0]
        servers[server_index] = service_times[i]
        wait_times[i] = 0
    else:
        # Add customer to queue
        queue.append(i)
        wait_times[i] = arrival_times[i] - arrival_times[queue[0]]
    
    # Update server times
    servers -= np.minimum(servers, arrival_times[i+1] - arrival_times[i])
    
    # Check if any customers have finished service
    finished_customers = np.where(servers == 0)[0]
    for j in finished_customers:
        if len(queue) > 0:
            # Assign customer from queue to server
            queue_index = queue.pop(0)
            servers[j] = service_times[queue_index]
            wait_times[queue_index] = arrival_times[queue_index] - arrival_times[queue[0]]
            
# Collect statistics
average_waiting_time = np.mean(wait_times)
average_queue_length = np.mean([len(queue) for i in range(num_customers)])
utilization = np.mean(servers > 0)

# Analyze the results
# You can use libraries such as matplotlib and seaborn to create histogram plots and density plots of the wait times and queue lengths.

In [ ]:
#generating inter arrival times using exponential distribution
inter_arrival_times = list(np.random.exponential(scale=1/l,size=ncust))

    #plotting data
plt.figure(figsize=(4,4))
sns.distplot(inter_arrival_times,kde=False,color='r',bins=20)
plt.title('Time between Arrivals')
plt.xlabel('Minutes')
plt.ylabel('Frequency')
sns.despine()
plt.show()

 # Generate random service times for each customer 
service_times = list(np.random.exponential(scale=1/µ,size=ncust))  

#service time distribution plot
plt.figure(figsize=(4,4))
sns.distplot(service_times,kde=False,bins=20)
plt.title('Service Times')
plt.xlabel('Minutes')
plt.ylabel('Frequency')
sns.despine()
plt.show()

In [ ]:
import simpy
import numpy as np
import matplotlib.pyplot as plt

# Define parameters of the queuing model
arrival_rate = 10.0  # customers per second
service_rate = 1.0   # seconds per customer
num_servers = 1000

# Define function to simulate customer arrivals
def customer_arrivals(env, arrival_rate):
    i = 0
    while True:
        yield env.timeout(np.random.exponential(1/arrival_rate))
        i += 1
        env.process(customer(env, i))

# Define function to simulate customer service
def customer(env, id):
    with server.request() as req:
        yield req
        service_time = np.random.exponential(service_rate)
        yield env.timeout(service_time)
        total_time = env.now - start_time
        queuing_times.append(total_time - service_time)

# Create the simulation environment
env = simpy.Environment()
server = simpy.Resource(env, capacity=num_servers)
queuing_times = []
start_time = env.now

# Start the simulation
env.process(customer_arrivals(env, arrival_rate))
env.run(until=1000)

# Analyze the results
mean_time = np.mean(queuing_times)
std_time = np.std(queuing_times)
plt.hist(queuing_times, bins=50)
plt.xlabel('Queuing Time')
plt.ylabel('Frequency')
plt.title(f'Distribution of Queuing Times (mean={mean_time:.2f}, std={std_time:.2f})')
plt.show()

#Feature Engineering of the Markov Chain Model

##1.State
The state of a Markov chain is the current position of the system. In the case of parking availability, the state could be "full", "half-full", or "empty".

In [ ]:
dataq.head(1)

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the data
data=dataq

# Create a LabelEncoder object
encoder = LabelEncoder()

# Encode the categorical column
data["VehiclePresent"] = encoder.fit_transform(data["VehiclePresent"])

In [ ]:
data.head(1)

In [ ]:
# Define the occupancy levels
FULL = 1.0
HALF_FULL = 0.5
EMPTY = 0.0

# Create a new column for the state
data["State"] = data["VehiclePresent"].apply(lambda x: "Full" if x >= FULL else "Half-Full" if x >= HALF_FULL else "Empty")

# Print the results
data.head(3)

## 2.Transition matrix/Transition Probabilities
 The transition matrix is a table that shows the probability of moving from one state to another. In the case of parking availability, the transition matrix could show the probability of a parking lot going from "full" to "half-full" or from "half-full" to "empty".We will calculate the transition probabilities between states for each AreaName. These probabilities represent the likelihood of moving from one occupancy state to another (e.g., full to half-full, half-full to empty) within each AreaName.

In [ ]:
# Create a new column for the previous occupancy level
data["Previous_Occupancy"] = data["State"].shift(1)

# Create a new column for the transition probability
data["Transition_Probability"] = data["State"].eq(data["Previous_Occupancy"])

# Calculate the transition probability matrix
transition_probability_matrix = data.groupby("AreaName")["Transition_Probability"].mean()

# Print the results
print(transition_probability_matrix.head(10))

The transition probability matrix shows the probability of an AreaName transitioning from one occupancy level to another. 

For example, the AreaName Chinatown has a 65% probability of transitioning from "Full" to "Full" and a 35% probability of transitioning from "Full" to "Half-Full".

##3.Initial distribution
The initial distribution is a probability distribution that represents the initial state of the system. In the case of parking availability, the initial distribution could show the probability that a parking lot is "full", "half-full", or "empty" at the beginning of the day. We calculate the expected or actual time it takes to reach specific occupancy states for the first time, starting from a given initial state. This parameter can help analyze the time required for certain occupancy levels to be reached in each Areaname.
We can take state from morning example when its empty to whenit was first occupied.

##4.Ergodicity and Reachability
This property ensures that all occupancy states can be reached from any other state within a AreaName,ensuring long-term exploration of the state space.

In [ ]:
# Remove the outlier Areaname=docklands from the transition probability matrix
transition_probability_matrix= transition_probability_matrix.drop(index=['Docklands'])

In [ ]:
# Check the index of the DataFrame if docklands is dropped
transition_probability_matrix.index

In [ ]:
# Convert the transition probability matrix to a NumPy array
transition_probability_matrix_numpy = np.array(transition_probability_matrix)

In [ ]:

# Add a dimension to the first array
transition_probability_matrix_numpy = transition_probability_matrix_numpy[:, np.newaxis]

# Concatenate the two arrays
transition_probability_matrix_numpy = np.concatenate((transition_probability_matrix_numpy, np.zeros((35,35))), axis=1)

# Calculate the eigenvalues and eigenvectors of the NumPy array
eigenvalues, eigenvectors = np.linalg.eig(transition_probability_matrix_numpy)

# Print the eigenvalues
print(eigenvalues)

In [ ]:
# Add a column of zeros to the matrix
transition_probability_matrix_numpy = np.hstack((transition_probability_matrix_numpy, np.zeros(69)))

# Reshape the NumPy array to a 2-dimensional array
transition_probability_matrix_numpy = transition_probability_matrix_numpy.reshape(69, 69)

# Calculate the eigenvalues and eigenvectors of the NumPy array
eigenvalues, eigenvectors = np.linalg.eig(transition_probability_matrix_numpy)

# Print the eigenvalues
print(eigenvalues)

In [ ]:
# Reshape the NumPy array to a 2-dimensional array
transition_probability_matrix_numpy = transition_probability_matrix_numpy.reshape(1, 69)

# Calculate the eigenvalues of the NumPy array
eigenvalues, eigenvectors = np.linalg.eig(transition_probability_matrix_numpy)

# Print the eigenvalues
print(eigenvalues)

In [ ]:
# Remove the last element from the array
transition_probability_matrix_numpy = transition_probability_matrix_numpy[:-1]
# Reshape the NumPy array to a 2-dimensional array
transition_probability_matrix_numpy = transition_probability_matrix_numpy.reshape(34,1)

In [ ]:
# Calculate the eigenvalues of the transition probability matrix

eigenvalues, eigenvectors = np.linalg.eig(transition_probability_matrix_numpy)
steady_state_vector = np.real(eigenvectors[:, np.isclose(eigenvalues, 1)])

# Normalize the steady-state probabilities
steady_state_probs = steady_state_vector / np.sum(steady_state_vector)

In [ ]:
# Check if all of the eigenvalues are less than 1
if all(eigenvalue < 1 for eigenvalue in eigenvalues):
    print("The system is ergodic.")
else:
    print("The system is not ergodic.")

f you have a non-square transition probability matrix and the goal is to estimate the steady-state probabilities or analyze ergodicity, it is true that you cannot directly compute eigenvalues using standard linear algebra methods. In such cases, it might be more appropriate to focus on alternative methods such as Markov Chain Monte Carlo (MCMC) sampling or other estimation techniques.

The purpose of calculating eigenvalues is typically to determine the steady-state probabilities of a Markov chain, where the eigenvector associated with the eigenvalue 1 represents the stationary distribution. However, for non-square transition matrices, this approach is not applicable.

Instead, using MCMC methods, you can simulate the Markov chain over multiple iterations, allowing it to converge towards a stationary distribution. By counting the frequency of visits to each state during the simulation, you can estimate the steady-state probabilities.

So, in the context of estimating steady-state probabilities or analyzing ergodicity with a non-square transition probability matrix, it would be appropriate to focus on the MCMC-based approach described earlier rather than pursuing eigenvalue calculations.

In [ ]:
# Assuming transition_prob_matrix is the transition probability matrix
num_iterations = 10000
num_areanames = transition_probability_matrix_numpy.shape[0]
state_counts = np.zeros(num_areanames)
current_state = np.random.choice(num_areanames)  # Initialize a random starting state

for _ in range(num_iterations):
    state_counts[current_state] += 1
    transition_probs = transition_probability_matrix_numpy[current_state]
    next_state = np.random.choice(num_areanames, p=transition_probs)
    current_state = next_state

steady_state_probs = state_counts / num_iterations

##5.Occupancy Duration Statistics
Analyze the duration of time spent in different occupancy states within each AreaName.The occupancy of the outlier AreaName is the most important feature for predicting the future state of the system. The outlier district has 99% of the occupancy information, so it is important to get this information accurately.

In addition to these parameters, I also saw fit to get the following information:

**The number of sensors in each district**. This information will help you to identify the districts that are most likely to be accurate.
**The occupancy information from the sensors**. This information will help you to train the Markov chain model.
**The time of day and day of week**. This information will help you to identify the times when the parking lots are most likely to be full or empty.

In [ ]:
import simpy

class M_M_1:
    def __init__(self, env, arrival_rate, service_rate):
        self.env = env
        self.arrival_rate = arrival_rate
        self.service_rate = service_rate
        self.server = simpy.Resource(env, capacity=1)
        self.queue = simpy.Container(env, init=0, capacity=float('inf'))
        self.arrival_process = env.process(self.arrival())
        self.service_process = env.process(self.service())
        self.waiting_times = []

    def arrival(self):
        while True:
            yield self.env.timeout(1 / self.arrival_rate)
            self.queue.put(1)
            if self.server.count == 0:
                self.service_process.interrupt()

    def service(self):
        while True:
            yield self.queue.get(1)
            start = self.env.now
            yield self.env.timeout(1 / self.service_rate)
            self.waiting_times.append(self.env.now - start)

You can then use this model to simulate an M/M/1 queue:

In [ ]:
env = simpy.Environment()
mm1 = M_M_1(env, arrival_rate=5, service_rate=2)
env.run(until=100)

Here is an example of a Python model for an M/M/1 queue with infinite buffer and FIFO service:

In [ ]:
#This code uses the SimPy library to simulate the M/M/1 queue.
# The server function represents the server and the customer_generator function generates customers
# that arrive at the queue according to an exponential distribution. 
#The arrival_rate and service_rate are set to 2 and 3 respectively, but can be adjusted as needed. 
#The simulation runs for 100 time units, but this can also be adjusted.

import simpy

def server(env, service_rate):
    while True:
        # Wait for a customer to arrive
        customer = yield env.timeout(random.expovariate(1/service_rate))
        # Service the customer
        yield env.timeout(random.expovariate(1/service_rate))

def customer_generator(env, arrival_rate, service_rate):
    while True:
        yield env.timeout(random.expovariate(1/arrival_rate))
        env.process(server(env, service_rate))

env = simpy.Environment()
arrival_rate = 2
service_rate = 3
env.process(customer_generator(env, arrival_rate, service_rate))
env.run(until=100)

Here is a sample implementation of an M/M/1 queue model (also known as an "Erlang-A" model) with an infinite buffer and first-in-first-out (FIFO) service discipline in Python:

In [ ]:
import random

class MM1Queue:
    def __init__(self, arrival_rate, service_rate):
        self.arrival_rate = arrival_rate
        self.service_rate = service_rate
        self.queue = []
        self.time = 0
        self.events = []

    def simulate(self, end_time):
        self.events = [(0, 'arrival')]
        while self.time < end_time:
            next_event = min(self.events, key=lambda x: x[0])
            self.time = next_event[0]
            if next_event[1] == 'arrival':
                self.handle_arrival()
            elif next_event[1] == 'departure':
                self.handle_departure()
            self.events.remove(next_event)

    def handle_arrival(self):
        arrival_time = self.time + random.expovariate(self.arrival_rate)
        self.events.append((arrival_time, 'arrival'))
        if not self.queue:
            departure_time = self.time + random.expovariate(self.service_rate)
            self.events.append((departure_time, 'departure'))
        self.queue.append(arrival_time)

    def handle_departure(self):
        self.queue.pop(0)
        if self.queue:
            departure_time = self.time + random.expovariate(self.service_rate)
            self.events.append((departure_time, 'departure'))

This model can be used by creating an instance of the MM1Queue class, setting the arrival rate and service rate, and then running the simulate method to run the simulation for a certain amount of time. For example:

In [ ]:
queue = MM1Queue(arrival_rate=5, service_rate=10)
queue.simulate(end_time=1000)

This will simulate an M/M/1 queue with an arrival rate of 5 customers per time unit and a service rate of 10 customers per time unit for 1000 time units.

Note that this is a simple example that does not include any statistics gathering or reporting, you can use the queue and events list to gather the relevant statistics you want after the simulation is done.

Here's an example implementation of the M/M/1 queuing model in Python for parking prediction:

In [ ]:
import math

def mm1_model(arrival_rate, service_rate, capacity):
    # Calculate the utilization factor
    utilization = arrival_rate / service_rate
    
    # Calculate the probability of zero customers in the system
    p0 = 1 - utilization
    
    # Calculate the average number of customers in the system
    l = utilization / (1 - utilization)
    
    # Calculate the average waiting time in the system
    w = l / arrival_rate
    
    # Calculate the probability of waiting in the system
    p_w = utilization
    
    # Calculate the probability of blocking
    p_block = math.pow(utilization, capacity) * p0
    
    # Return the results
    return l, w, p_w, p_block

This function takes three input parameters: the arrival rate (in customers per unit of time), the service rate (in customers per unit of time), and the capacity of the parking lot (the number of parking spots available). It returns four output parameters: the average number of customers in the system, the average waiting time in the system, the probability of waiting in the system, and the probability of blocking (i.e., the probability that all parking spots are occupied).

To use this function, you would first need to estimate the arrival rate and service rate based on historical data or other sources of information. You would also need to determine the capacity of the parking lot. Then you could call the function like this:

In [ ]:
arrival_rate = 10 # customers per minute
service_rate = 12 # customers per minute
capacity = 50 # parking spots
l, w, p_w, p_block = mm1_model(arrival_rate, service_rate, capacity)
print("Average number of customers in the system: ", l)
print("Average waiting time in the system: ", w)
print("Probability of waiting in the system: ", p_w)
print("Probability of blocking: ", p_block)

# M/M/M MODEL

To implement the M/M/M queuing model for parking prediction in Python, we can use the simpy package, which is a discrete-event simulation framework. Here is an example code:

In [ ]:
!pip install SimPy

In [ ]:
import simpy
import numpy as np

arrival_rate=aver_at
service_rate=avg_serv_t

class ParkingLot:
    def __init__(self, env, n, m, arrival_rate, service_rate):
        self.env = env
        self.n = n
        self.m = m
        self.arrival_rate = arrival_rate
        self.service_rate = service_rate
        self.parking_spaces = simpy.Resource(env, capacity=n)
        self.waiting_times = []

    def park_car(self):
        with self.parking_spaces.request() as req:
            yield req
            waiting_time = self.env.now - self.arrival_time
            self.waiting_times.append(waiting_time)
            service_time = np.random.exponential(1/self.service_rate)
            yield self.env.timeout(service_time)

    def run(self, run_time):
        self.env.process(self.generate_cars())
        self.env.run(until=run_time)

    def generate_cars(self):
        while True:
            inter_arrival_time = np.random.exponential(1/self.arrival_rate)
            yield self.env.timeout(inter_arrival_time)
            self.arrival_time = self.env.now
            self.env.process(self.park_car())

    def occupancy(self):
        return (self.n - len(self.parking_spaces.queue)) / self.n

    def utilization(self):
        return sum([len(x) for x in self.parking_spaces.users])/self.m

    def average_waiting_time(self):
        return np.mean(self.waiting_times)

    def probability_of_waiting(self):
        return len([x for x in self.waiting_times if x > 0])/len(self.waiting_times)

In [ ]:
import simpy
import numpy as np

class ParkingLot:
    # define the ParkingLot class (code omitted for brevity)

# create a simulation environment
 env = simpy.Environment()

# set the simulation parameters
n = 20 # number of parking spaces
m = 2 # number of attendants
arrival_rate = 5 # average number of cars arriving per hour
service_rate = 10 # average time to service a car in minutes

# create an instance of the ParkingLot class
parking_lot = ParkingLot(env, n, m, arrival_rate/60, service_rate)

# run the simulation for 8 hours
parking_lot.run(run_time=8*60)

# analyze the results
print(f"Occupancy: {parking_lot.occupancy():.2%}")
print(f"Utilization: {parking_lot.utilization():.2%}")
print(f"Average waiting time: {parking_lot.average_waiting_time():.2f} minutes")
print(f"Probability of waiting: {parking_lot.probability_of_waiting():.2%}")

In this code, we define a ParkingLot class that simulates the queuing system. The __init__ method initializes the parameters of the model, such as the number of parking spaces n, the number of servers m, the arrival rate arrival_rate, and the service rate service_rate. It also creates a simpy.Resource object that represents the parking spaces.

The park_car method simulates the process of parking a car. It requests a parking space from the simpy.Resource object, calculates the waiting time, and generates a service time from an exponential distribution with mean 1/service_rate.

The run method starts the simulation and runs it for a specified time run_time. The generate_cars method generates cars according to a Poisson process with rate arrival_rate, and for each car, it calls the park_car method as a subprocess.

The occupancy method calculates the occupancy rate of the parking lot, which is the proportion of occupied parking spaces. The utilization method calculates the utilization rate of the servers, which is the proportion of time they are busy. The average_waiting_time method calculates the average waiting time of customers who had to wait. The probability_of_waiting method calculates the probability that a customer has to wait.

To use the ParkingLot class, we can create an instance with the desired parameters and run the simulation:

In [ ]:
n = 50  # number of parking spaces
m = 3   # number of servers
arrival_rate = 2  # customers per minute
service_rate = 3  # customers per minute

env = simpy.Environment()
parking_lot = ParkingLot(env, n, m, arrival_rate, service_rate)
parking_lot.run(120)  # run simulation for 60 minutes

#print("Occupancy rate:", parking_lot)

Here's an example implementation of the M/M/M queuing model for parking prediction in Python, using the numpy and scipy libraries for scientific computing:

In [ ]:
import numpy as np
from scipy.stats import poisson, expon

def parking_mmm_model(n, m, lambda_, mu):
    """M/M/M queuing model for parking prediction"""
    
    # Calculate utilization rate
    rho = lambda_ / (m * mu)
    
    # Calculate expected number of customers in system
    num_customers = (rho ** n) * ((1 - rho) / (1 - rho ** (n + 1)))
    
    # Calculate expected waiting time
    wait_time = num_customers / (lambda_ * (1 - rho))
    
    # Calculate probability of waiting
    prob_wait = rho ** n * (1 - rho) / (1 - rho ** (n + 1))
    
    # Calculate probability of all spaces occupied
    prob_full = rho ** n
    
    return num_customers, wait_time, prob_wait, prob_full

# Example usage
n = 1000000 # number of parking spaces
m = servers  # number of servers
lambda_ = aver_at  # arrival rate (per minute)
mu = avg_serv_t  # service rate (per minute)

num_customers, wait_time, prob_wait, prob_full = parking_mmm_model(n, m, lambda_, mu)

print(f"Expected number of customers in system: {num_customers:.2f}")
print(f"Expected waiting time: {wait_time:.2f} mins")
print(f"Probability of waiting: {prob_wait:.2f}")
print(f"Probability of all spaces occupied: {prob_full:.2f}")

This code defines a function parking_mmm_model that takes as input the number of parking spaces n, the number of servers m, the arrival rate lambda_, and the service rate mu, and returns the expected number of customers in the system, the expected waiting time, the probability of waiting, and the probability of all parking spaces being occupied.

The function first calculates the utilization rate rho, which is the key parameter in the M/M/M queuing model. It then uses this parameter to calculate the expected number of customers in the system, the expected waiting time, and the probabilities of waiting and all spaces being occupied.

The example usage section shows how to call the function with some sample inputs, and prints the results. Note that the expected waiting time is in hours, since the arrival rate and service rate are specified in units of customers per hour.

Sure, here's an updated version of the M/M/M parking prediction model in Python where the number of servers is set to 1100:

In [ ]:
import numpy as np
from scipy.stats import poisson, expon

def parking_mmm_model(n, m, lambda_, mu):
    """M/M/M queuing model for parking prediction"""
    
    # Calculate utilization rate
    rho = lambda_ / (m * mu)
    
    # Calculate expected number of customers in system
    num_customers = (rho ** n) * ((1 - rho) / (1 - rho ** (n + 1)))
    
    # Calculate expected waiting time
    wait_time = num_customers / (lambda_ * (1 - rho))
    
    # Calculate probability of waiting
    prob_wait = rho ** n * (1 - rho) / (1 - rho ** (n + 1))
    
    # Calculate probability of all spaces occupied
    prob_full = rho ** n
    
    return num_customers, wait_time, prob_wait, prob_full

# Example usage with 1100 servers
n = 100  # number of parking spaces
m = 1100  # number of servers
lambda_ = 2  # arrival rate (per hour)
mu = 3  # service rate (per hour)

num_customers, wait_time, prob_wait, prob_full = parking_mmm_model(n, m, lambda_, mu)

print(f"Expected number of customers in system: {num_customers:.2f}")
print(f"Expected waiting time: {wait_time:.2f} hours")
print(f"Probability of waiting: {prob_wait:.2f}")
print(f"Probability of all spaces occupied: {prob_full:.2f}")

The only change is to set the m parameter to 1100 instead of 3. The other inputs (number of parking spaces, arrival rate, and service rate) are the same as in the previous example.

Note that with 1100 servers, the utilization rate will likely be very low (unless the arrival rate is extremely high), which means that the parking lot will be highly underutilized. In practice, it is unlikely that a parking lot would have 1100 servers (i.e., parking attendants) for only 100 parking spaces.

#Bayesian model

##1.Prior distribution
 A non-informative prior distribution, such as a uniform distribution, would be appropriate for this data. This is because we do not have any prior information about the occupancy levels in the Areanames.
 We have used beta distribution instead

In [ ]:
import numpy as np
import scipy.stats as stats

alpha = 2
beta = 2

outlier_occupancy_prior = np.random.beta(alpha, beta)
occupancy_rates_prior = np.random.beta(alpha, beta, size=35)
sensor_reliability_prior = np.random.beta(alpha, beta)
transition_probs_prior = np.random.dirichlet(alpha=[0.5, 0.5, 0.5])  # assume all areanames have the same 3 states

##2.Likelihood function 
The likelihood function should be based on the observed data. In this case, the likelihood function would be the probability of observing the data that we did, given the parameters of the model.

In [ ]:
# Define the discrete random variable also
# Define the likelihood function
likelihood_function = stats.poisson(1)

In [ ]:
from scipy.stats import binom

def likelihood(outlier_occupancy, occupancy_rates, sensor_reliability, transition_probs):
    # Compute the likelihood based on the model parameters and the observed data
    # For example, if you have occupancy_data and sensor_data:
    likelihood = binom.pmf(sensor_data, occupancy_data, sensor_reliability)
    return likelihood

##3.Posterior distribution
The posterior distribution is the probability of the parameters of the model, given the observed data. The posterior distribution can be calculated using Bayes' theorem.

In [ ]:
import scipy.stats as stats

In [ ]:
# Calculate the posterior distribution
posterior_distribution =(transition_probs_prior*likelihood_function(data["VehiclePresent"]))

# Print the posterior distribution

In [ ]:
pip install pymc3

In [ ]:
import pymc3 as pm

# Define the Bayesian model
with pm.Model() as model:
    # Priors for the parameters
    outlier_occupancy = pm.Beta('outlier_occupancy', alpha, beta)
    occupancy_rates = pm.Beta('occupancy_rates', alpha, beta, shape=35)
    sensor_reliability = pm.Beta('sensor_reliability', alpha, beta)
    transition_probs = pm.Dirichlet('transition_probs', alpha=[0.5, 0.5, 0.5])  # Example with 3 states

    # Likelihood function
    likelihood = pm.Binomial('likelihood', n=sensor_data, p=sensor_reliability, observed=occupancy_data)

    # Perform MCMC sampling
    trace = pm.sample(1000, tune=500)

# multiple linear regression

Python code to demonstrate how multiple linear regression can be used to predict parking occupancy based on external factors:


In this example, we first load the parking occupancy data and external factors data, and then merge them based on the date column. We then split the merged data into training and testing sets, and define the independent variables (weather, time of day, day of week, and holiday) and dependent variable (occupancy).

Next, we create a multiple linear regression model using scikit-learn's LinearRegression class, and fit it to the training data. We then use the trained model to predict the parking occupancy for the test data, and evaluate the accuracy of the model using mean squared error.

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Load the parking occupancy and external factors data
parking_data = pd.read_csv('parking_data.csv')
external_factors = pd.read_csv('external_factors.csv')

# Merge the parking occupancy and external factors data
merged_data = pd.merge(parking_data, external_factors, on='date')

# Split the data into training and testing sets
train_data = merged_data.loc[merged_data['date'] < '2022-01-01']
test_data = merged_data.loc[merged_data['date'] >= '2022-01-01']

# Define the independent variables and dependent variable
X_train = train_data[['weather', 'time_of_day', 'day_of_week', 'holiday']]
y_train = train_data['occupancy']

X_test = test_data[['weather', 'time_of_day', 'day_of_week', 'holiday']]
y_test = test_data['occupancy']

# Create a multiple linear regression model and fit it to the training data
reg_model = LinearRegression().fit(X_train, y_train)

# Use the trained model to predict the parking occupancy for the test data
y_pred = reg_model.predict(X_test)

# Evaluate the accuracy of the model using mean squared error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean squared error: {mse}")

# autoregressive integrated moving average (ARIMA)

demonstrate how the ARIMA model can be used to forecast future parking occupancy based on historical occupancy data:

In this example, we first load the historical parking occupancy data and convert the date column to a datetime object and set it as the index. We then split the data into training and testing sets.

Next, we create an ARIMA model using the statsmodels library's ARIMA class, with the order parameter set to (2, 1, 1) to specify an ARIMA(2,1,1) model. We then fit the ARIMA model to the training data.

We use the ARIMA model to forecast the parking occupancy for the test data using the forecast method. Finally, we evaluate the accuracy of the model using mean squared error.

In [ ]:
#we then check if our arrival times are stationary
#to check stationarity we draw a scatter plot of cumulative customers(y-axis)
#and that of cumulative arrival times(x-axis)

In [ ]:
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA

# Load the historical parking occupancy data
#parking_data = pd.read_csv('parking_data.csv')

# Convert the date column to a datetime object and set it as the index
dataq['Day'] = pd.to_datetime(dataq['Day'])
datak= dataq.set_index('Day')

# Split the data into training and testing sets
train_data = dataq.loc[datak.index < '1']
test_data = dataq.loc[datak.index >= '7']

# Create an ARIMA model and fit it to the training data
arima_model = ARIMA(train_data, order=(2, 1, 1)).fit()

# Use the ARIMA model to forecast the parking occupancy for the test data
forecast_data = arima_model.forecast(steps=len(test_data))

# Evaluate the accuracy of the model using mean squared error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(test_data, forecast_data)
print(f"Mean squared error: {mse}")

In this example, we first load the parking occupancy data and convert the date column to datetime format and set it as the index. We then split the data into training and testing sets.

Next, we fit an ARIMA model to the training data using statsmodels' ARIMA class with an order of (1, 1, 1), which specifies an autoregressive model of order 1, a differencing of order 1, and a moving average model of order 1.

We then use the fitted model to forecast the parking occupancy for the test data using the forecast method, which returns an array of predicted values.

Finally, we plot the predicted and actual occupancy values for the test data using matplotlib.

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Load the parking occupancy and external factors data
parking_data = pd.read_csv('parking_data.csv')
external_factors = pd.read_csv('external_factors.csv')

# Merge the parking occupancy and external factors data
merged_data = pd.merge(parking_data, external_factors, on='date')

# Split the data into training and testing sets
train_data = merged_data.loc[merged_data['date'] < '2022-01-01']
test_data = merged_data.loc[merged_data['date'] >= '2022-01-01']

# Define the independent variables and dependent variable
X_train = train_data[['weather', 'time_of_day', 'day_of_week', 'holiday']]
y_train = train_data['occupancy']

X_test = test_data[['weather', 'time_of_day', 'day_of_week', 'holiday']]
y_test = test_data['occupancy']

# Create a multiple linear regression model and fit it to the training data
reg_model = LinearRegression().fit(X_train, y_train)

# Use the trained model to predict the parking occupancy for the test data
y_pred = reg_model.predict(X_test)

# Evaluate the accuracy of the model using mean squared error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean squared error: {mse}")

# deep learning:LSTM Model and  cnn

In [ ]:
#First, let's import the necessary libraries:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM, Conv1D, MaxPooling1D, Flatten
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#Next, let's load the parking availability data and preprocess it:
# Load the parking availability data
data = pd.read_csv('parking_data.csv')

# Split the data into training and testing sets
train_data = data[:8000]
test_data = data[8000:]

# Scale the data
scaler = MinMaxScaler(feature_range=(0, 1))
train_data_scaled = scaler.fit_transform(train_data)
test_data_scaled = scaler.transform(test_data)

In [ ]:
#Now, let's define the LSTM model:
# Define the LSTM model
lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(train_data_scaled.shape[1], 1)))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dense(units=1))
lstm_model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
#Next, let's train the LSTM model:
# Train the LSTM model
X_train = []
y_train = []
for i in range(60, len(train_data_scaled)):
    X_train.append(train_data_scaled[i-60:i, 0])
    y_train.append(train_data_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
lstm_model.fit(X_train, y_train, epochs=50, batch_size=32)

In [ ]:
#Now, let's define the CNN model:
# Define the CNN model
cnn_model = Sequential()
cnn_model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(train_data_scaled.shape[1], 1)))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(units=1))
cnn_model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
#Next, let's train the CNN model:
# Train the CNN model
X_train_cnn = []
y_train_cnn = []
for i in range(60, len(train_data_scaled)):
    X_train_cnn.append(train_data_scaled[i-60:i, 0])
    y_train_cnn.append(train_data_scaled[i, 0])
X_train_cnn, y_train_cnn = np.array(X_train_cnn), np.array(y_train_cnn)
X_train_cnn = np.reshape(X_train_cnn, (X_train_cnn.shape[0], X_train_cnn.shape[1], 1))
cnn_model.fit(X_train_cnn, y_train_cnn, epochs=50, batch_size=32)

In [ ]:
#Finally, let's use the trained models to predict parking availability:
# Predict parking availability using the LSTM model
X_test = []
for i in range(60, len(test_data_scaled)):
    X_test.append(test_data_scaled[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

how you can use LSTM and CNN models for parking availability prediction based on the study by Ma et al. (2021). Please note that this code is for illustration purposes only and may require modification based on your specific data and requirements.

In [ ]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from sklearn.preprocessing import MinMaxScaler

# Load the parking data
df = pd.read_csv('parking_data.csv')

# Preprocess the data
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df['parking_availability'].values.reshape(-1, 1))

# Split the data into training and testing sets
train_size = int(len(scaled_data) * 0.8)
test_size = len(scaled_data) - train_size
train_data = scaled_data[0:train_size, :]
test_data = scaled_data[train_size:len(scaled_data), :]

# Define the LSTM model
lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(1, 1)))
lstm_model.add(Dropout(0.2))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=1))

# Train the LSTM model
lstm_model.compile(loss='mean_squared_error', optimizer='adam')
lstm_model.fit(train_data, epochs=100, batch_size=32)

# Define the CNN model
cnn_model = Sequential()
cnn_model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(1, 1)))
cnn_model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(50, activation='relu'))
cnn_model.add(Dense(1))

# Train the CNN model
cnn_model.compile(loss='mean_squared_error', optimizer='adam')
cnn_model.fit(train_data, epochs=100, batch_size=32)

# Predict parking availability using the trained models
lstm_predictions = lstm_model.predict(test_data)
lstm_predictions = scaler.inverse_transform(lstm_predictions)
cnn_predictions = cnn_model.predict(test_data)
cnn_predictions = scaler.inverse_transform(cnn_predictions)

# Evaluate the models
lstm_rmse = np.sqrt(np.mean(np.power((test_data - lstm_predictions), 2)))
cnn_rmse = np.sqrt(np.mean(np.power((test_data - cnn_predictions), 2)))

print("LSTM RMSE: ", lstm_rmse)
print("CNN RMSE: ", cnn_rmse)

This code assumes that you have a CSV file containing the parking availability data and the column name for parking availability data is 'parking_availability'. You can replace the filename and column name in the code with your own data.

The code uses the MinMaxScaler to normalize the data and split it into training and testing sets. It then defines the LSTM and CNN models and trains them using the training data. Finally, it uses the trained models to predict parking availability for the test data and evaluates the models using the root mean squared error (RMSE).

# Support Vector Regression (SVR) model for prediction

In [ ]:
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Load the data
df = pd.read_csv('data.csv')

# Split the data into features and target
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the SVR model
svr_model = SVR(kernel='linear', C=1.0, epsilon=0.2)
svr_model.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = svr_model.predict(X_test)

# Evaluate the model
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: ", rmse)

In [ ]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from sklearn.preprocessing import MinMaxScaler

# Load the parking data
df = dataq

# Preprocess the data
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df['VehiclePresent'].values.reshape(-1, 1))

# Split the data into training and testing sets
train_size = int(len(scaled_data) * 0.8)
test_size = len(scaled_data) - train_size
train_data = scaled_data[0:train_size, :]
test_data = scaled_data[train_size:len(scaled_data), :]

# Define the LSTM model
lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(1, 1)))
lstm_model.add(Dropout(0.2))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=1))

# Train the LSTM model
lstm_model.compile(loss='mean_squared_error', optimizer='adam')
lstm_model.fit(train_data, epochs=100, batch_size=32)

# Define the CNN model
cnn_model = Sequential()
cnn_model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(1, 1)))
cnn_model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
cnn_model.add(MaxPooling1D(pool_size=2))
cnn_model.add(Flatten())
cnn_model.add(Dense(50, activation='relu'))
cnn_model.add(Dense(1))

# Train the CNN model
cnn_model.compile(loss='mean_squared_error', optimizer='adam')
cnn_model.fit(train_data, epochs=100, batch_size=32)

# Predict parking availability using the trained models
lstm_predictions = lstm_model.predict(test_data)
lstm_predictions = scaler.inverse_transform(lstm_predictions)
cnn_predictions = cnn_model.predict(test_data)
cnn_predictions = scaler.inverse_transform(cnn_predictions)

# Evaluate the models
lstm_rmse = np.sqrt(np.mean(np.power((test_data - lstm_predictions), 2)))
cnn_rmse = np.sqrt(np.mean(np.power((test_data - cnn_predictions), 2)))

print("LSTM RMSE: ", lstm_rmse)
print("CNN RMSE: ", cnn_rmse)